version: '3.4'

services:

    sqldata:
        image: microsoft/mssql-server-linux:latest

    rabbitmq:
        image: rabbitmq:3-management-alpine


    authorizationservice:
        image: authorizationservice

        build:
          context: .
          dockerfile: Services/Authorization/AuthorizationService/Dockerfile
        
        depends_on:
            - sqldata


    catalogservice:
        image: catalogservice

        build:
          context: .
          dockerfile: Services/Catalog/CatalogService/Dockerfile
        
        depends_on:
            - sqldata
            - authorizationservice
            - rabbitmq

    transactionservice:
        image: transactionservice

        build:
          context: .
          dockerfile: Services/Transaction/Transaction.Service/Dockerfile
        
        depends_on:
            - sqldata
            - authorizationservice
            - catalogservice
                

    
    mobilegateservice:
        image: mobilegateservice
        build:
            context: .
            dockerfile: Gateways/MobileApiGateway/Dockerfile
            target: development
        depends_on:
            - authorizationservice
            - catalogservice
            - transactionservice

    
    admingateservice:
        image: admingateservice
        build:
            context: .
            dockerfile: Gateways/AdministrationGateway/Dockerfile
            target: development

        depends_on:
            - authorizationservice
            - catalogservice
            - transactionservice