// <auto-generated />
using System;
using Catalog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

namespace Catalog.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CatalogContext))]
    partial class CatalogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.Login", b =>
                {
                    b.Property<Guid>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<Point>("LoginLocation")
                        .HasColumnType("geography");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginId");

                    b.HasIndex("UserId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectComment", b =>
                {
                    b.Property<Guid>("ObjectCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ObjectCommentId");

                    b.HasIndex("LoginId");

                    b.HasIndex("ObjectId");

                    b.ToTable("ObjectComment");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectImpression", b =>
                {
                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ViewedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ObjectId", "LoginId", "ViewedAtUtc");

                    b.HasIndex("LoginId");

                    b.ToTable("ObjectImpressions");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectLike", b =>
                {
                    b.Property<Guid>("ObjectLikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LikedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.HasKey("ObjectLikeId");

                    b.HasIndex("LoginId");

                    b.HasIndex("ObjectId");

                    b.ToTable("ObjectLike");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectPhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.HasKey("PhotoId");

                    b.HasIndex("ObjectId");

                    b.ToTable("ObjectPhotos");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectTag", b =>
                {
                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ObjectId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ObjectTags");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectView", b =>
                {
                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ViewedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ObjectId", "LoginId", "ViewedAtUtc");

                    b.HasIndex("LoginId");

                    b.ToTable("ObjectView");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.OfferedObject", b =>
                {
                    b.Property<int>("OfferedObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentTransactionType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerLoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OfferedObjectId");

                    b.HasIndex("OwnerLoginId");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhotoId")
                        .HasColumnType("int");

                    b.Property<int>("TagStatus")
                        .HasColumnType("int");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.TagPhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PhotoId");

                    b.HasIndex("TagId")
                        .IsUnique();

                    b.ToTable("TagPhotos");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<Guid>("ReceipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReceivingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReturnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("ObjectId");

                    b.HasIndex("ReceipientId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.Login", b =>
                {
                    b.HasOne("Catalog.ApplicationCore.Entities.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectComment", b =>
                {
                    b.HasOne("Catalog.ApplicationCore.Entities.Login", "Login")
                        .WithMany("Comments")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.ApplicationCore.Entities.OfferedObject", "Object")
                        .WithMany("Comments")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectImpression", b =>
                {
                    b.HasOne("Catalog.ApplicationCore.Entities.Login", "Login")
                        .WithMany("Impressions")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.ApplicationCore.Entities.OfferedObject", "Object")
                        .WithMany("Impressions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectLike", b =>
                {
                    b.HasOne("Catalog.ApplicationCore.Entities.Login", "Login")
                        .WithMany("Likes")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.ApplicationCore.Entities.OfferedObject", "Object")
                        .WithMany("Likes")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectPhoto", b =>
                {
                    b.HasOne("Catalog.ApplicationCore.Entities.OfferedObject", "Object")
                        .WithMany("Photos")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectTag", b =>
                {
                    b.HasOne("Catalog.ApplicationCore.Entities.OfferedObject", "Object")
                        .WithMany("Tags")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.ApplicationCore.Entities.Tag", "Tag")
                        .WithMany("Objects")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.ObjectView", b =>
                {
                    b.HasOne("Catalog.ApplicationCore.Entities.Login", "Login")
                        .WithMany("Views")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.ApplicationCore.Entities.OfferedObject", "Object")
                        .WithMany("Views")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.OfferedObject", b =>
                {
                    b.HasOne("Catalog.ApplicationCore.Entities.Login", "OwnerLogin")
                        .WithMany("OwnedObjects")
                        .HasForeignKey("OwnerLoginId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.TagPhoto", b =>
                {
                    b.HasOne("Catalog.ApplicationCore.Entities.Tag", "Tag")
                        .WithOne("Photo")
                        .HasForeignKey("Catalog.ApplicationCore.Entities.TagPhoto", "TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.ApplicationCore.Entities.Transaction", b =>
                {
                    b.HasOne("Catalog.ApplicationCore.Entities.OfferedObject", "Object")
                        .WithMany("Transactions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.ApplicationCore.Entities.User", "Receipient")
                        .WithMany("MeAsReceipient")
                        .HasForeignKey("ReceipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
